In [1]:
import torch

from nichejepa.masks.multigene import MaskCollator

In [3]:
mask = MaskCollator(seq_len=20,
                    n_targets=2,
                    target_mask_size=3,
                    context_mask_size=10,
                    n_contexts=1,
                    has_cls=True # False
                   )

In [4]:
target_mask, target_mask_complement = mask._sample_gene_mask(
    non_zero_seq_len=10,
    mask_size=3)

print(target_mask)
print(target_mask_complement)

tensor([0, 2, 3, 4])
tensor([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=torch.int32)


In [5]:
context_mask, context_mask_complement = mask._sample_gene_mask(
    non_zero_seq_len=10,
    mask_size=5,
    valid_token_masks=[target_mask_complement]
)

print(context_mask)
print(context_mask_complement)

tensor([0, 1, 5])
tensor([1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=torch.int32)


In [6]:
batch = [(torch.tensor([11, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), # input tokens
          torch.tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), # input seg label
          "CT A"), # input cell type
         (torch.tensor([11, 6, 4, 3, 2, 1, 4, 10, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
          torch.tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
          "CT B")]

collated_batch, collated_masks_context, collated_masks_target = mask(batch)
print(collated_batch)
print(collated_masks_context)
print(collated_masks_target)

[tensor([[11,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [11,  6,  4,  3,  2,  1,  4, 10,  3,  2,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0]]), tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), ('CT A', 'CT B')]
[tensor([[ 0,  1,  2,  3,  4],
        [ 0,  1,  5,  9, 10]])]
[tensor([[0, 7, 8, 9],
        [0, 6, 7, 8]]), tensor([[0, 7, 8, 9],
        [0, 2, 3, 4]])]
