In [1]:
%load_ext autoreload
%autoreload 2

In [198]:
import torch

from nichejepa.masks.multigene import MaskCollator

In [217]:
mask = MaskCollator(seq_len=20,
                    n_targets=2,
                    target_mask_size=3,
                    context_mask_size=10,
                    n_contexts=1,
                    has_cls=True # False
                   )

In [200]:
target_mask, target_mask_complement = mask._sample_gene_mask(
    non_zero_seq_len=10,
    mask_size=3)

print(target_mask)
print(target_mask_complement)

tensor([4, 5, 6])
tensor([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=torch.int32)


In [201]:
context_mask, context_mask_complement = mask._sample_gene_mask(
    non_zero_seq_len=10,
    mask_size=5,
    valid_token_masks=[target_mask_complement]
)

print(context_mask)
print(context_mask_complement)

tensor([2, 3])
tensor([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=torch.int32)


In [238]:
batch = (torch.tensor([11, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
         torch.tensor([11, 6, 4, 3, 2, 1, 4, 10, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

collated_batch, collated_masks_context, collated_masks_target = mask(batch)
print(collated_batch)
print(collated_masks_context)
print(collated_masks_target)

tensor([[11,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [11,  6,  4,  3,  2,  1,  4, 10,  3,  2,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0]])
[tensor([[ 1,  8,  9, 10],
        [ 4,  5,  6, 10]])]
[tensor([[5, 6, 7],
        [1, 2, 3]]), tensor([[2, 3, 4],
        [7, 8, 9]])]
